### PR TITLE
Integrated proper designs for skip button

### PR DESCRIPTION
**Pull request by YaroslavKryvko**
@VerizonAdPlatforms/mobile-sdk-developers: Ready for review.

- Integrated proper assets
- Increased size a bit according to new designs
- Made skip button colorable with mainColor
- Made pressed state for skip button to be 75% alpha
screen shot 2019-01-17 at 15 50 50
screen shot 2019-01-17 at 15 50 38

[JIRA](https://jira.ops.aol.com/browse/OMSDK-2094)

### CODE REVIEW

**Review by AleksanderLevadniy — DISMISSED** [review]
👍 Looks nice

**Comment by YaroslavKryvko** [comment]
@AleksanderLevadniy, @AndriiMoskvin, please check final designs

**Comment by AndriiMoskvin** [comment]
👍

**Review by AleksanderLevadniy — DISMISSED** [review]
Please use `float ht_px = TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, ht, getResources().getDisplayMetrics());` approach

**Review by AleksanderLevadniy — APPROVED** [review]
🚢 🇮🇹and 🔐

**Pull request merged**
